#!/usr/bin/env python3
from palindrome_thuston.phrase import Phrase


with open("phrases.txt") as file:
#    lines = file.readlines()
#    for line in lines:
#        if Phrase(line).ispalindrome():
#            print(f"Palindrome detected: {line.strip()}")

#palindrome_content = [line for line in lines if Phrase(line).ispalindrome()]
    palindromes = [line for line in file.readlines()
        if Phrase(line).ispalindrome()]

palindrome_content = "".join(palindromes)
print(palindrome_content, end="")

with open("palindromes.txt", "w") as file:
    file.writelines(palindrome_content)
